---
title: "Introduction to Rtpca"
author: "Nils Kurzawa"
date: "`r format(Sys.time(), '%d %B, %Y')`"
package: Rtpca
output:
    BiocStyle::html_document
vignette: >
    %\VignetteIndexEntry{Introduction to Rtpca}
    %\VignetteEngine{knitr::rmarkdown}
    %VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE}
library(TPP)
library(Rtpca)
```

```{r}
data("ecoli_stat_vs_exp_config")
data("ecoli_stat_vs_exp_cytosol_data")
data("ecoli_string_id_df")
```


```{r}
ecoliTrData <- tpptrImport(configTable = ecoli_stat_vs_exp_config, 
                           data = ecoli_stat_vs_exp_cytosol_data,
                           idVar = "protein_id")
```

```{r}
ecoliDataNorm <- tpptrNormalize(data = ecoliTrData)
```

```{r}
ecoliTPCA <- runTPCA(
    objList = ecoliDataNorm$normData[1:3], #ecoliDataNorm$normData[1:3],
    ppiAnno = ecoli_string_id_df
)
```

```{r}
plotPPiRoc(ecoliTPCA, computeAUC = TRUE)
```

## PPis within complexes

```{r}
ecoliTrData <- tpptrImport(configTable = ecoli_stat_vs_exp_config, 
                           data = ecoli_stat_vs_exp_cytosol_data,
                           idVar = "gene_name")
```

```{r}
load("/Users/kurzawa/repos/Rtpca/data/ecoli_complex_ppis.rda")
ecoliTPCA <- runTPCA(
    objList = ecoliTrData[1:3], #ecoliDataNorm$normData[1:3],
    ppiAnno = ecoli_complex_ppis
)
```

```{r}
plotPPiRoc(ecoliTPCA, computeAUC = TRUE)
```